version: "3.8"
services:

  # Database for KeyCloak Auth Service
  postgres:
    image: postgres:14.1-alpine
    container_name: auth_db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    networks:
      - main-network

  redis:
    image: redis:latest
    container_name: auth_redis
    ports:
      - 6380:6379
    networks:
      - main-network

  app:
    build: .
    container_name: auth-service
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      REDIS_URL: redis://auth_redis:6379
      HOST: "${HOST}"
      LOG_LEVEL: "${LOG_LEVEL}"
    ports:
      - 8001:8000
    networks:
      - main-network
    links:
      - postgres:auth-db
      - redis:auth-service

volumes:
  db:
    driver: local

networks:
  main-network:
